version: '3'
services:
  myshiny:
    build: 
        context: ./code
        target: final-islocaldevelopment-true

    volumes:
      - .:/workspace:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
  
