version: '3.7'
services:
  api:
    build:
      context: ./backend_fastapi
      target: final-islocaldevelopment-true

    volumes:
      - .:/workspace:cached
 
    command: /bin/sh -c "while sleep 1000; do :; done"

